# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.14
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=1.5.8.7
maven_group=com.luxof.lapisworks
archives_base_name=lapisworks

# Dependencies
fabric_version=0.92.6+1.20.1
hexcasting_version=0.11.4
cca_version=5.2.3
fabric_kotlin_version=1.13.7+kotlin.2.2.21
trinkets_version=3.7.2
hextended_version=2.0.1
hexical_hexdoc_version=1.5.0
hierophantics_hexdoc_version=1.3.5
# jar files for libs isn't a good idea if you like transitive depends :sadhowdy:
player_animator_version = 1.0.2-rc1+1.20
vs2_version=2.4.0+75bf0ce873
vscore_version=1.1.0+7ec91c1e3a
emi_version = 1.1.22+1.20.1
hexcessible_version=0.3.1

# whatever I'm doing to Gradle goes here
forge_version=47.4.20
# hello non-windows user!
java17path=C:/Program Files/Eclipse Adoptium/jre-17.0.19.10-hotspot/bin/java.exe
dependency_regex=\\"https://[^/]+/([^\\"]+)
